import './globals.scss'
import { Space_Mono } from 'next/font/google'
import TheHeader from '@/components/Header'
import TheFooter from '@/components/Footer'
import Link from 'next/link'

const sm = Space_Mono({ subsets: ['latin'] , weight:'400' })

export const metadata = {
  title: 'webshop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={sm.className} >
        <TheHeader/>
        <div className="wrapp">
        <aside>
          <div className='aside_menu'>
           <Link className='aside_menu_item' href={'/phones'}>Phones</Link>
           <Link className='aside_menu_item' href={'/tablets'}>Tablets</Link>
           <Link className='aside_menu_item' href={'/laptops'}>Laptops</Link>
          </div>
        </aside>
        <main>
        {children}
        </main>
        </div>
        <TheFooter/>
        </body>
    </html>
  )
}
