import './globals.scss'
import { Space_Mono } from 'next/font/google'
import TheHeader from '@/components/header'
import TheFooter from '@/components/footer'
import Link from 'next/link'

const sm = Space_Mono({ subsets: ['latin'] , weight:'400' })

export const metadata = {
  title: 'webshop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  suppressHydrationWarning={true} >
        <TheHeader/>
        <div className="wrapp">
        <aside>
          <ul>
            <li><Link href={'/phones'}>Phones</Link></li>
            <li><Link href={'/tablets'}>Tablets</Link></li>
            <li><Link href={'/laptops'}>Laptops</Link></li>
          </ul>
        </aside>
        <main>
        {children}
        </main>
        </div>
        <TheFooter/>
        </body>
    </html>
  )
}
