import './globals.scss'
import { Space_Mono } from 'next/font/google'
import TheHeader from '@/components/Header'
import TheFooter from '@/components/Footer'
import Link from 'next/link'
import {Navigation} from '../components/Navigation';

import { Providers } from '@/store/provider';


const sm = Space_Mono({ subsets: ['latin'] , weight:'400' })

export const metadata = {
  title: 'webshop',
  description: 'Generated by create next app',
}

const navItems = [
  {label: 'Phones', href: "/phones"},
  {label: 'Teblets', href: "/tablets"},
  {label: 'Laptops', href: "/laptops"}
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body  className={sm.className} >
        <TheHeader/>
        <div className="wrapp">
        <aside>
          <Navigation navLinks = {navItems}/>
        </aside>
        <main>
          <Providers>
          {children}
          </Providers>
        </main>
        </div>
        <TheFooter/>
        </body>
    </html>

  )
}
